# Inventory Management Deployment with LoadBalancer Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: $CONTAINER_REGISTRY/inventory_management:$VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: DATABASE_URL
              value: "postgresql://week09_2myt_user:tGJmJNOA1liJV7rE4uuqQ5gtu6QFKIWB@dpg-cs30t3pu0jms73920mh0-a.oregon-postgres.render.com/week09_2myt"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - port: 80
      targetPort: 7000
